### ISSUE TITLE
Maybe a little marketing in "webpack-isomorphic-tools" ?

### ISSUE THREAD

**Issue by aight8** [halt-hammerzeit/universal-webpack#12]
**can be deleted I oversee it there (it's hidden behind a link I don't excepted :))**

Since this library is the successor maybe you could write a comment on the webpack-isomorphic-tools readme that people should checkout this project too for a more native solution.

https://github.com/halt-hammerzeit/webpack-isomorphic-tools

The more people use this library the better could it be (tested/contribution).

**Comment by halt-hammerzeit** [comment]
Ok, that would be appropriate.
Rewrote the introduction in the README.
https://github.com/halt-hammerzeit/webpack-isomorphic-tools/commit/55975b6a5f373143ff08c7a9d4d19ece7bb980ce
