### ISSUE TITLE
server object is empty

### ISSUE THREAD

**Issue by aight8** [halt-hammerzeit/universal-webpack#13]
In ```import { server } from 'universal-webpack';``` the server object is empty.

**universal-webpack** exports:

```JS
{ server: undefined,
  server_configuration: [Function: server_configuration],
  client_configuration: undefined,
  prepare: undefined,
  serverConfiguration: [Function: server_configuration],
  clientConfiguration: undefined }
```

**Comment by halt-hammerzeit** [comment]
Yes, already fixed that, try the latest one
https://github.com/halt-hammerzeit/universal-webpack/commit/4450debe556c5239fde15feeadb8d2e15f69dbf9

**Comment by aight8** [comment]
Ah yes it's fixxed
