### ISSUE TITLE
Usage with davezuko's starter kit

### ISSUE THREAD

**Issue by janoist1** [halt-hammerzeit/universal-webpack#17]
I'm trying to create a universal React Redux project based on some of the fundamentals of [davezuko's starter kit](https://github.com/davezuko/react-redux-starter-kit). Found your stuff but it seems to be very unclear how to achieve it so I'm turning to you here for some instructions with the configuration.
I also opened a question [here](http://stackoverflow.com/questions/38396987/how-to-use-universal-webpack-with-webpack-dev-server-as-middleware)
Thanks in advance!

**Comment by halt-hammerzeit** [comment]
> it seems to be very unclear how to achieve it

Everything becomes clear after you learn things

**Comment by janoist1** [comment]
Thanks, I'm trying. But can't do everything at once.

**Comment by halt-hammerzeit** [comment]
> In the documentation there is the following - which I want to avoid having some generated stuff like build/server/server.js - It'd be nice to have it on the fly like the Webpack-dev-server does

Then use another library

**Comment by halt-hammerzeit** [comment]
> But can't do everything at once.

You're not supposed to

**Comment by janoist1** [comment]
> Then use another library
Your library look decent to me so that I've chosen it. Are you saying it is not possible to achieve what I want with it? - thats also a solution.

**Comment by halt-hammerzeit** [comment]
This library requires compiling server-side code into a file on disk.
If you are looking for a way to avoid that then that would be another library.

**Comment by janoist1** [comment]
I see, thanks.

**Comment by halt-hammerzeit** [comment]
You may have a look at `webpack-isomorphic-tools`
https://github.com/halt-hammerzeit/webpack-isomorphic-tools
It doesn't compile it to a file on disk, but it does create a `webpack-assets.json` file on disk.
