### ISSUE TITLE
Documentation for source/server.js missing react-router import?

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/universal-webpack#18]
Is the documentation for source/server.js missing a react-router import? 
I see react-router.match but no earlier reference to react-router.

Also the documentation says "Math" in the comment where you probably mean "Match".

**Comment by halt-hammerzeit** [comment]
@adailey14 Yes, that was pseudo-code. It means it could be `react-router` match or a more sophisticated thing like `redux-router` or `react-router-redux`
