### ISSUE TITLE
Feature request - return promise from server.js

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/universal-webpack#21]
It would be useful for me if you could return the wait_for_file promise from server.js (line 20 of server.js). Then I could access the server I am creating and do things with it (such as mounting it into a koa parent instance). I think it might be useful in general.

I am trying to have a page-server run as a separate process in development, the way you have it setup in webpack-react-redux-isomorphic-render-example, but then mount the page-server into the web-server in production, so it can all run under one port. This is so I can deploy to Heroku servers, which only allow you to use one port.

What do you think?

**Comment by halt-hammerzeit** [comment]
Oh, sure, that should be `return wait_for_file` instead of `wait_for_file`.
Install the latest version for the fix, it should be working.

So I'm guessing your return a Koa middleware from the `server()` function, and then `.use()` that middleware on the main Koa app?
Or is there some way to mount a child Koa application inside a parent Koa application?

Yesterday I've also introduced an extension point for `page-server`: 
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/33906f9f787a0bae88067aae593788a2b09a55dc/source/page-server/web%20server.js#L94-L102
Maybe it can serve your needs too.

**Comment by adailey14** [comment]
Awesome thanks for updating that.

For mounting, I read that you can use koa-mount to mount one koa app within
another as a middleware, but haven't actually tried it yet:
https://github.com/koajs/mount. I am going to try that and if it doesn't
work then return a koa middleware like you said. Ideally koa-mount will
work so I can use your webserver from the react-isomorphic-render project.
I'm trying to stick with your implementation as much as possible, since it
is cleaner than when I do my own.

I will check out the extension point for page-server, I think it may be
very handy.

**Comment by halt-hammerzeit** [comment]
Ok.
I might also give the current `page-server` architecture a thought and maybe export a `server-render` function which would basically be the already present rendering function
https://github.com/halt-hammerzeit/react-isomorphic-render/blob/master/source/page-server/render.js#L18
That function would return a Promise, and so it could be usable with anything be it Koa, Express or any other library.
That can be the task for tomorrow.

**Comment by adailey14** [comment]
Yes I think that would be good.

**Comment by adailey14** [comment]
Hi again. I am running into trouble, I think because halt-hammerzeit/web-service is using koa ^2.0.0, while halt-hammerzeit/react-isomorphic-render is using koa 1.1.2. koa-mount's current release is support koa 1.x, and they have a "next" branch supporting 2.x.

I will see if I can get this to work, but it might be worth updating react-isomorphic-render to koa 2.x at some point for consistency.

**Comment by halt-hammerzeit** [comment]
I migrated `react-isomorphic-render` to Koa v2 recently, have you updated the package?

**Comment by adailey14** [comment]
Oh oops I didn't notice that, thanks!

**Comment by adailey14** [comment]
FYI I just got everything to work, mounting the page-server within the web-service for production. 

3 "gotchas" were:

1. I had to use koa-mount@next version to support koa 2.x
2. I had to pass detect_locale: true option when creating web-service, otherwise the mounted page-server would crash, since the ctx object passed through from the parent koa application did not have the getLocaleFromQuery() function.
3. I had to make page-server/start export a function to generate the server like this:
export default () => server(configuration, settings);
And then call that function in page-server/web server.js and web-server/web server.js
Otherwise the server would get started multiple times since I need to import it in both page-server/web server.js and web-server/web server.js.

**Comment by halt-hammerzeit** [comment]
2. Oh, I get it. I was going to remove that option first but seems that it has its uses. Anyway I'll extract routing in a separate middleware soon. These two days were non-stop coding and debugging (mostly fixing `react-isomorphic-render` bugs)
3. Didn't get the idea without the code, but I guess I don't have too.

**Comment by halt-hammerzeit** [comment]
Extracted server-side rendering into an exported `render` function in the latest version of the package.
https://github.com/halt-hammerzeit/react-isomorphic-render#without-proxying

**Comment by halt-hammerzeit** [comment]
Removed `preferred_locale` from `render` function parameters.
Now it only takes the same parameters as webpage server + `request` original HTTP request.
`preferred_locale` is not passed in this case and it's up to the developer to detect the preferred locale.
