### ISSUE TITLE
More instructions about exclude_from_externals

### ISSUE THREAD

**Issue by hufeihxw** [halt-hammerzeit/universal-webpack#25]
Hi @halt-hammerzeit, 

Thanks for this awesome lib first.

I ran into a problem when my app requires some css file from a library in node_modules, it has taken me quite some time to figure out [exclude_from_externals](https://github.com/halt-hammerzeit/universal-webpack#advanced-configuration) can deal with this

(I had to look in to [server configuration.js](https://github.com/halt-hammerzeit/universal-webpack/blob/master/source/server%20configuration.js)'s source code, seen your comments there)

From the docs I read, I can understand its about webpack, people shall learn this setting from webpack docs, but still a little more instructions can make people aren't webpack experts like me 's life easier
 
maybe something like:

`When requiring non-js files from node_modules, you must mark them as non-external so webpack buildings for server side can process them`

**Comment by halt-hammerzeit** [comment]
Hello.
`exclude_from_externals` option is described in the README, but it is only described for the use case of JS files.
I didn't think that someone would use it for CSS.
I have updated the README with your suggested instructions

**Comment by hufeihxw** [comment]
Looks great to me, thanks
