### ISSUE TITLE
Define enviroment variable whether if it's a server or client build

### ISSUE THREAD

**Issue by aight8** [halt-hammerzeit/universal-webpack#27]
With webpacks DefinePlugin

There are serveral use cases this can be helpful to include some piece of code from the shared libararies only in a specific build.

It could be named "TARGET" = "client" || "server"

In the code then you can use for example:
```JS
if (process.env.TARGET == 'server') {
    apiBaseURL = '127.0.0.1:80'
    ...handleCookie passing...
}
```
etc.

This don't exposes server side code to the user.

**Comment by halt-hammerzeit** [comment]
I didn't understand what you said

**Comment by Vincz** [comment]
I think that @aight8 would like to have some kind of global variables to be able to know if the code is running on the client or on the server.
Something like:

    if (_server_) {
        console.log("I'm executed on the server"); // Never logged on the browser
    }

    if (_client_) {
        console.log("I'm executed in the browser"); // Never logged on the server
    }

With the help of Webpack DefinePlugin (https://github.com/webpack/docs/wiki/list-of-plugins#defineplugin) the finals builds will include only their related part.

**Comment by halt-hammerzeit** [comment]
This could be achieved in your webpack server-side configuration:

```js
import { server_configuration } from 'universal-webpack'
import settings from './universal-webpack-settings'
import configuration from './webpack.config'

const config = server_configuration(configuration, settings)

config.plugins.push(new webpack.DefinePlugin
({
  __SERVER__ : JSON.stringify(true)
}))

export default config
```

**Comment by sebfek** [comment]
Thanks for the code, thats exactly what I mean. No way to integrate it to something similar to the library itself? Benefits: Less userland code and same in every app.
It's a small thing but why should NOT this in library? Makes it for newcomes easier.

**Comment by halt-hammerzeit** [comment]
Well, I'm not sure it's needed as part of the library.
Maybe if enough people leave comments here then I may reconsider.

**Comment by sebfek** [comment]
👍
