### ISSUE TITLE
__dirname is / in server modules

### ISSUE THREAD

**Issue by nickm-scribestar** [halt-hammerzeit/universal-webpack#30]
Hey, thanks for this module, trying to get css modules and webpack working with some server side rendered react components at the moment.

I set it up just like the instructions in the readme and now my express code can't find the jade views as __dirname is now '/'

my express code looks something like:

```
app.set('views', __dirname + 'views')

// ... other stuff

res.status(200).render('index.ejs', {reactOutput, initialState})
```

which of course now fails because my views directory can't be found.

What have I done wrong? :)

**Comment by halt-hammerzeit** [comment]
This issue has been encountered before
https://github.com/halt-hammerzeit/universal-webpack/issues/16
Webpack sets `__dirname` to `/`

https://github.com/webpack/webpack/issues/1599#issuecomment-186841345
They say that this works:

```js
node: {
  __dirname: false,
  __filename: false,
}
```

So I suggest you do the following:

in your server configuration do this:

```js
import { server_configuration } from 'universal-webpack'
import settings from './universal-webpack-settings'
import configuration from './webpack.config'

config = server_configuration(configuration, settings)

config.node = {
  __dirname: false,
  __filename: false
}

export default config
```

And post back on results

**Comment by nickm-scribestar** [comment]
yup confirmed that worked great - thanks loads!

**Comment by halt-hammerzeit** [comment]
I'm including this in the library then.
Install the latest version and tell me if it works without the hack:
`npm install universal-webpack@latest --save`

**Comment by nickm-scribestar** [comment]
Yup, removed my hack and can confirm v0.1.40 fixes it. Thanks again.

**Comment by nickm-scribestar** [comment]
Reading the [referenced issue](https://github.com/halt-hammerzeit/universal-webpack/issues/16) I can't help thinking actually your recommended solution in this [comment ](https://github.com/halt-hammerzeit/universal-webpack/issues/16#issuecomment-231597678) might be the better way to go anyway though in the end?

**Comment by halt-hammerzeit** [comment]
Actually, I don't think I understood what he was saying in that issue report.
And I don't remember why I answered him that way.

**Comment by nickm-scribestar** [comment]
okay yes thinking about it the same server module that is loading in my jade view would also need to do the react server rendering so a separation wouldn't be possible.
