### ISSUE TITLE
Webpack 2 support

### ISSUE THREAD

**Issue by cyberwombat** [halt-hammerzeit/universal-webpack#35]
Hi. Does this work with Webpack 2?

**Comment by halt-hammerzeit** [comment]
It should

**Comment by Heliosophist** [comment]
> It should

Just tested it and throws an error if you use the new syntax for loaders:
```
module: {
  rules: {
    ...
  }
} 
```
intead of the old v1 way: 
```
module: {
  loaders: {
    ...
  }
} 
```

The top of the error stack trace shows us the line where a check is made in the module
```
// line 11 in source/loaders.js
for (let loader of configuration.module.loaders)
{
...
```

The error:
> TypeError: undefined is not iterable!
>     at module.exports.require.getIterator (/<project_path>/node_modules/core-js/library/modules/core.get-iterator.js:5:40)
>     at find_style_loaders (/<project_path>/node_modules/universal-webpack/source/loaders.js:11:2)
>    .....

Webpack 2 still supports the old syntax btw....

**Comment by halt-hammerzeit** [comment]
@Heliosophist fixed in the latest release

**Comment by halt-hammerzeit** [comment]
FYI the newest `0.2.0` release now only supports Webpack 2.
It works for my project.
If you find any bugs in the new version then create an issue.
