### ISSUE TITLE
readme.md commands do not work

### ISSUE THREAD

**Issue by davibe** [halt-hammerzeit/universal-webpack#36]
In all of your command examples i.e.
```webpack-dev-server --hot --inline --config "./webpack.config.client.js" --port XXXX --colors --display-error-details```

you should postpone `babel-node` otherwise node.js does not support `import` ES6 stuff. Unless i am missing something ?

**Comment by halt-hammerzeit** [comment]
I don't understand what you're saying

**Comment by davibe** [comment]
it's a noob observation. Instead of writing `webpack-dev-server --hot --inline --config "./webpack.config.client.js" --port XXXX --colors --display-error-details` -> you could write -> `babel-node webpack-dev-server --hot --inline --config "./webpack.config.client.js" --port XXXX --colors --display-error-details` otherwise the syntax propsed for webpack.config.* would trigger import errors (`import .. from ..`)

**Comment by halt-hammerzeit** [comment]
Oh, I see.
Well, this example is meant for ES5 syntax for simplicity sake.
For ES6 there are 3 options:
* using `babel-node`
* using `webpack.config.client.babel.js` magic filename
* using `require('babel-register'); require('es6.config')` in the config
I wouldn't enforce any of them

**Comment by davibe** [comment]
Looks like i did not know about the magic filename thing!
