### ISSUE TITLE
More detailed example for separating a react rendering service from the main code

### ISSUE THREAD

**Issue by tokenvolt** [halt-hammerzeit/universal-webpack#39]
I can't grasp how to separate those things and the docs are a bit confusing. My initial understanding was to have a nodemon server for monitoring a server rendering and then have another node server with a proxy configured to serve requests from the nodemon server. But I can't understand how this would help with making things more faster, because there is still a node server with nodemon to watch the files. 

Can you provide a more detailed example on how to do this or maybe a more detailed explanation for how things should work?

**Comment by halt-hammerzeit** [comment]
I don't understand you.
Можете писать по-русски, если хотите.

**Comment by tokenvolt** [comment]
Спасибо за ответ. Я пытаюсь разобраться, как реализовать https://github.com/halt-hammerzeit/universal-webpack#separate-react-rendering-service-from-the-main-code. Вот, например, что подразумевается должен делать react_service? Как его запускать?

**Comment by halt-hammerzeit** [comment]
Я переписал этот фрагмент.
Стало ли понятнее?
`reactRenderingService` - делает Server Side Rendering реакта (рендерит страницы на сервере, как PHP)

**Comment by tokenvolt** [comment]
Я правильно понимаю, что reactRenderingService мониторится с помощью того же nodemon?

**Comment by halt-hammerzeit** [comment]
Да, конечно

**Comment by halt-hammerzeit** [comment]
нет постоянного TCP соединения с прокси-сервером - соединение мимолётное.
возможно http-proxy что-то решил оставить на потом, но я не думаю, что он бы так сделал.

когда постите логи, правилом хорошего тона является постинг полного лога.

**Comment by tokenvolt** [comment]
Полный лог
![image](https://cloud.githubusercontent.com/assets/1728072/19907633/5ce9c5b0-a088-11e6-9b64-324eedd891be.png)

**Comment by halt-hammerzeit** [comment]
Это не полный лог.
Это какой-то кусок.

**Comment by tokenvolt** [comment]
Больше не получается)
![image](https://cloud.githubusercontent.com/assets/1728072/19908494/4aba7520-a08c-11e6-8e69-57bff28521b1.png)

**Comment by halt-hammerzeit** [comment]
ну вот, сразу при запуске он уже ошибку выдаёт.
исходный код постите.

**Comment by tokenvolt** [comment]
Это при изменении кода.
```js
var path = require('path')
var http = require('http')
var express = require('express')
var httpProxy = require('http-proxy')

const app = express()
const proxy = httpProxy.createProxyServer({})

app.use(function(request, response) {
  proxy.web(request, response, { target:'http://localhost:3000' })
})

app.listen(5000, () => console.log("Listen..."))
```

**Comment by halt-hammerzeit** [comment]
м, ну, значит они реально соединение устанавливают.
попробуйте ловить ошибку четвёртым параметром:

```js

  proxy.web(request, response, { target:'http://localhost:3000' }, error => console.error(error))
```

**Comment by tokenvolt** [comment]
Да, отлавливать можно, но live-reload все равно работать не будет, так как браузер теряет соединение с webpack и страницу приходится перегружать вручную.

**Comment by halt-hammerzeit** [comment]
с кем теряет соединение браузер?
webpack процесс тут вообще ни при чём.

**Comment by tokenvolt** [comment]
Как-то можно получить live-reload при использовании проксирования?
![image](https://cloud.githubusercontent.com/assets/1728072/19909359/ffab8cb4-a08f-11e6-9904-379e1dbabf03.png)

**Comment by halt-hammerzeit** [comment]
Ну вот, он не может достучаться до 3001-ого, видимо.
3000-ный и 5000-ный тут вообще ни при чём.

**Comment by tokenvolt** [comment]
Ок, спасибо, буду разбираться.
