### ISSUE TITLE
modules config in webpack 2

### ISSUE THREAD

**Issue by diegohaz** [halt-hammerzeit/universal-webpack#41]
I have a webpack config with the following:
```js
resolve: {
    modules: ['app', 'node_modules'],
}
```

But it seems to not work with `universal-webpack`. I've tried using `alias`, but it still doesn't work.

**Comment by halt-hammerzeit** [comment]
All modules are `external` for server-side configuration, therefore Node.js doesn't know how to `require('app/...')`.
Use `exclude_from_externals` setting
https://github.com/halt-hammerzeit/universal-webpack#advanced-configuration

**Comment by halt-hammerzeit** [comment]
Or use `resolve.alias` instead

**Comment by halt-hammerzeit** [comment]
FYI the newest `0.2.0` release now only supports Webpack 2.
It works for my project.
If you find any bugs in the new version then create an issue.
