### ISSUE TITLE
Webpack loaders do not work when using `require`/`import` in nested components

### ISSUE THREAD

**Issue by mieszko4** [halt-hammerzeit/universal-webpack#44]
I have a react app which uses `react-router` and `babel`. I use code splitting in my router.
Each route is assigned to some component which then includes other components and assets (`.scss`, `.png`).

When I include just components without any assets all works perfect.
When I include assets (e.g. `logo.png`) directly on a code-split component (e.g. `Home.js`) it works perfect, too.

However, the problem appears when I include assets in a component that is used by `Home.js`, e.g. `Navigation.js` includes `logo.png`.

Is this a bug, or is it not supported?
Could you guide me where in the code loaders are applied to `require`/`import`? Perhaps I could do a fork.

**Comment by halt-hammerzeit** [comment]
> Could you guide me where in the code loaders are applied to require/import? 

I don't understand you

**Comment by mieszko4** [comment]
So I guess your lib hacks `require` and applies loaders defined in webpack config, right? It seems they are not applied for nested components and I am trying to figure out why.

**Comment by halt-hammerzeit** [comment]
> So I guess your lib hacks require and applies loaders defined in webpack config, right?

No it doesn't

**Comment by mieszko4** [comment]
I will do some more research and get back to you.

**Comment by mieszko4** [comment]
The problem was with webpack's path `resolve` configuration.
Before implementing `universal-webpack` on our project I used `root` but I needed to add `alias` to make path resolution work for `require`.

I must have done adding `alias` wrong. After fixing it all works like a charm :smiley: !
