### ISSUE TITLE
universal-webpack setup for current webpack project, need help

### ISSUE THREAD

**Issue by iroy2000** [halt-hammerzeit/universal-webpack#46]
Thanks for this project.

I'm trying to follow the readme and have almost the same settings, but I'm having the following error when I run `babel-node "./src/server/startServer"`   

TypeError: Cannot read property 'path' of undefined
    at chunk_info_file_path (/Users/roy/development/projects/react-redux-boilerplate/node_modules/universal-webpack/source/chunks.js:5:19)
    at /Users/roy/development/projects/react-redux-boilerplate/node_modules/universal-webpack/source/server.js:22:37

And also, I don't know if I'm setting up correctly ( the `webpack.config.client.js` and `webpack.config.server.js` seems okay, at least not throwing error )

Here is my start server

```
import { server } from 'universal-webpack'
import settings from '../../universal-webpack-settings'
// `configuration.context` and `configuration.output.path` are used
import configuration from '../../webpack.config.babel'

// somehow I need this or it will throw error that my config has no context
configuration.context = configuration.default.context

server(configuration, settings)

```

Thanks for helping, I wonder if there is any gitter or chat channel to talk about problems ?

**Comment by halt-hammerzeit** [comment]
https://github.com/halt-hammerzeit/universal-webpack/blob/master/source/chunks.js#L5

This could mean that the `webpack_configuration` you're passing to the library is `undefined`.
`console.log` it to make sure.

**Comment by iroy2000** [comment]
Let me check, and get back to this thread.

**Comment by iroy2000** [comment]
Ok, I think I found out where the issue is coming from.

Do you see any problem in my `startServer.js` script ??  I'm just testing it out right now with very basic setting, my goal is to get it working :)

```
// express.js
import path from 'path'
import express from 'express'

import { match, RouterContext } from 'react-router'

import React from 'react/dist/react.min'
import { Provider } from 'react-redux'
import { renderToString } from 'react-dom/server'

// react-router
import routes from '../js/routes'

// Redux
import store from '../js/redux/configureStore'

// The server code must export a function
// (`parameters` may contain some miscellaneous library-specific stuff)
export default function(parameters)
{

    const app = express();

    // React application rendering
    app.use((req, res) =>
    {
      match({ routes, location }, (err, redirectLocation, renderProps) => {
        if (err)
        {
            res.status(500)
            return res.send(`Server error ${err}`)
        }

        // Render React page

        const InitialView = (
          <Provider store={store}>
            <RouterContext {...renderProps} />
          </Provider>
        )

        const componentHTML = renderToString(InitialView)

        res.status(200)
        res.send('<!doctype html>' + '\n' + ReactDOM.renderToString(<Html>{componentHTML}</Html>))
      })
    })

    // Start the HTTP server
    app.listen(3000, () => {
      console.log('starting server')
    })
}


```

**Comment by halt-hammerzeit** [comment]
Well, it exports a function, so it should work, even with es6's `default` export.
If you share a sample project with the reproduction instructions and the error message then maybe I would have a look.

**Comment by iroy2000** [comment]
Thanks, here is the steps

https://github.com/iroy2000/react-redux-boilerplate/tree/adding-ssr-support

I basically follow your basic setup, and I'm very new to universal-webpack, basically run the following command in the PROJECT_ROOT ( same as the tutorial, but please let me know if I missed anything )

```
NODE_ENV=production webpack --config "./webpack.config.client.babel.js" --colors --display-error-details

NODE_ENV=production webpack --config "./webpack.config.server.babel.js" --colors --display-error-details

NODE_ENV=production babel-node "./src/server/startServer"
```

**Comment by halt-hammerzeit** [comment]
```
zsh: command not found: webpack
```

You should move these commands to `package.json` `scripts` so that they work with locally installed webpack

**Comment by iroy2000** [comment]
Hi @halt-hammerzeit 

I added a script  `npm run ssr-debug` which is doing that

"ssr-debug": "NODE_ENV=production webpack --config './webpack.config.client.babel.js' --colors --display-error-details && NODE_ENV=production webpack --config './webpack.config.server.babel.js' --colors --display-error-details && NODE_ENV=production babel-node './src/server/startServer'"

**Comment by halt-hammerzeit** [comment]
@iroy2000 
> ➜  react-redux-boilerplate git:(adding-ssr-support) npm run ssr-debug

> react-redux-boilerplate@0.6.2 ssr-debug /Users/kuchumovn/work/react-redux-boilerplate
> NODE_ENV=production webpack --config './webpack.config.client.babel.js' --colors --display-error-details && NODE_ENV=production webpack --config './webpack.config.server.babel.js' --colors --display-error-details && NODE_ENV=production babel-node './src/server/startServer'


Yes, that outputs the error:
```
TypeError: i.default is not a constructor
```

Now split that command into smaller parts and find out which one of them causes the error.

**Comment by iroy2000** [comment]
It is the last one that caused the error, let me split that up.

**Comment by halt-hammerzeit** [comment]
Now, look at the stack trace and tell me, in which file and on which line is the error

```
TypeError: i.default is not a constructor
    at Object.t.default (/Users/kuchumovn/work/react-redux-boilerplate/build/server/server.js:4:163)
    at /Users/kuchumovn/work/react-redux-boilerplate/node_modules/universal-webpack/source/server.js:53:11
    at run (/Users/kuchumovn/work/react-redux-boilerplate/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
    at /Users/kuchumovn/work/react-redux-boilerplate/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/Users/kuchumovn/work/react-redux-boilerplate/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

**Comment by iroy2000** [comment]
I believe it is coming from this line

https://github.com/iroy2000/react-redux-boilerplate/blob/adding-ssr-support/src/server/server.js#L22

function(e,t,r){"use strict";function n(e){return e&&e.__esModule?e:{"default":e}}Object.defineProperty(t,"__esModule",{value:!0}),t["default"]=function(e){**var t=new i["default"]**;t.use(function(e,t){(0,l.match)({routes:p["default"],location:location},function(e,r,n){if(e)return t.status(500),t.send("Server error "+e);var u=s["default"].createElement(c.Provider,{store:x["default"]},s["default"].createElement(l.RouterContext,n)),o=(0,d.renderToString)(u);t.status(200),t.send("<!doctype html>\n"+ReactDOM.renderToString(s["default"].createElement(Html,null,o)))})}),t.listen(3e3,function(){console.log("starting server")})};var u=r(/*! path */27),o=(n(u),r(/*! express */25)),i=n(o),l=r(/*! react-router */5),a=r(/*! react/dist/react.min */29),s=n(a),c=r(/*! react-redux */4),d=r(/*! react-dom/server */28),f=r(/*! ../js/routes */13),p=n(f),m=r(/*! ../js/redux/configureStore */10),x=n(m)},/*!************************!*\

**Comment by iroy2000** [comment]
I just coded my webpack server config from scratch and it works fine.

I still like the concept of config generator though, I will come back to it later. But since now doing it from scratch works and I feel more comfortable that way. 

Let's close this ticket then. 

Thanks.

**Comment by halt-hammerzeit** [comment]
Well, you should have been turned minification off, then it would be

```
TypeError: _express2.default is not a constructor
    at Object.exports.default (/Users/kuchumovn/work/react-redux-boilerplate/build/server/server.js:59:14)
    at /Users/kuchumovn/work/react-redux-boilerplate/node_modules/universal-webpack/source/server.js:53:11
    at run (/Users/kuchumovn/work/react-redux-boilerplate/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
    at /Users/kuchumovn/work/react-redux-boilerplate/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/Users/kuchumovn/work/react-redux-boilerplate/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Which means it didn't like this line:

```js
    const app = new express()
```

And even when  `new` is removed it would still complain.

```js
console.log('express', express)
```

Would give:

```
@@@@@@@@@@@@@@@ express { basicAuth: [Getter],
  bodyParser: [Getter],
  compiler: [Getter],
  compress: [Getter],
  cookieParser: [Getter],
  csrf: [Getter],
  directory: [Getter],
  errorHandler: [Getter],
  favicon: [Getter],
  limit: [Getter],
  logger: [Getter],
  methodOverride: [Getter],
  profiler: [Getter],
  query: [Getter],
  responseTime: [Getter],
  router: [Getter],
  session: [Getter],
  static: [Getter],
  staticCache: [Getter],
  vhost: [Getter],
  version: '2.5.11',
  createServer: [Function],
  HTTPServer: [Function: HTTPServer],
  HTTPSServer: [Function: HTTPSServer],
  Route: [Function: Route],
  view: { [Function: View] register: [Function], compile: [Function], lookup: [Function] },
  View: { [Function: View] register: [Function], compile: [Function], lookup: [Function] } }
```

Which means you have a really weird `express` installed.

Then I would direct you at your `package.json` and you would find that `express` dependency is missing from there.

Then you would install `express@latest`, remove `new` and the error would disappear.

And all those things are the things you could do by yourself if you had a bit of patience and diligence but I guess you don't.

**Comment by iroy2000** [comment]
Ha, let me do that again, as I said, I really like that config generation concept.  Thanks.

**Comment by iroy2000** [comment]
Thanks, that's actually really helpful.
