### ISSUE TITLE
Import CSS file from node modules throws exception on server side render

### ISSUE THREAD

**Issue by aight8** [halt-hammerzeit/universal-webpack#49]
```
(function (exports, require, module, __filename, __dirname) { .class-name

SyntaxError: Unexpected token .
```

**Comment by halt-hammerzeit** [comment]
The it doesn't on the client side too, possibly because your webpack configuration doesn't process node_modules with css-loader

**Comment by aight8** [comment]
It worked and works on client.
My css related webpack config are:
```
const extractStyle = new ExtractTextPlugin(mainOutputCssFile);
```

```
{
        test: new RegExp(escapeRegExp(mainScssFile) + '$'),
        loader: extractStyle.extract(['css-loader', 'sass-loader']),
      },
      {
        test: /\.scss$/,
        loaders: ['style-loader', 'css-loader', 'sass-loader'],
        exclude: [path.resolve(__dirname, 'src', 'scss', mainScssFile)],
      },
      {
        test: /\.css$/,
        loaders: ['style-loader', 'css-loader'],
      },
```

**Comment by aight8** [comment]
I think I got it.
As default the node modules directory is marked as external on server build. So no loaders are used at all on server side for node modules only when you mark the package in the "exclude_from_externals" list. The problem is, I only want load css files with a loader not the whole module.

**Comment by halt-hammerzeit** [comment]
Yes, currently you must exclude it from `external`s in order for it to be processed by Webpack loaders.
You can write a regular expression which will only match the files you need.
You can use regexpal.com
