### ISSUE TITLE
TypeError: rule.use.map is not a function

### ISSUE THREAD

**Issue by drejohnson** [halt-hammerzeit/universal-webpack#56]
I can't figure out how to get the serverConfiguration to work. The clientConfiguration work as expected. Any suggestion on what I'm doing work or overlooking? I'm also using Typescript only.

```
rule.use = rule.use.map(parse_loader)
TypeError: rule.use.map is not a function
```
Here's a gist of my Webpack config: https://gist.github.com/drejohnson/84183f8ad7efad32115b0e39cdf8d85b

**Comment by halt-hammerzeit** [comment]
You can make up a sample project illustrating the issue (without any typescript) and I could have a look tomorrow

**Comment by halt-hammerzeit** [comment]
Try the latest version, should work now.

**Comment by drejohnson** [comment]
That works! Thanks!
