### ISSUE TITLE
Problem with style on the server side

### ISSUE THREAD

**Issue by bertho-zero** [halt-hammerzeit/universal-webpack#61]
Hi, I tried to install universal-webpack on my repo beginning with the dev part and I'm stuck and I do not know why, I push the project here: https://github.com/bertho-zero/react-redux-universal-hot-example/tree/universal-webpack

With just an `npm i` and `npm run dev` could see the problem right away.

Thank you!

**Comment by bertho-zero** [comment]
"halt-hammerzeit closed this 16 hours ago" Thanks !

**Comment by halt-hammerzeit** [comment]
Someone has to be the guy whose issues get closed right away.
And why would you think a random guy would stop by and get into sorting your own business out instead of paying attention to his own business.

**Comment by bertho-zero** [comment]
This is a repo you know and it seems more convenient to navigate in a rep github rather than paste the config here, not knowing where the problem comes from. This is a problem that I have already seen in the issues without successfully correcting it.

https://github.com/halt-hammerzeit/universal-webpack/issues/49
https://github.com/halt-hammerzeit/universal-webpack/issues/34

I fixed this with these lines in my '`start-server.babel.js`':

```js
require.extensions['.less'] = function() {};
require.extensions['.scss'] = function() {};
require.extensions['.png'] = function() {};
```

**Comment by halt-hammerzeit** [comment]
Yeah, sure, "Problem with style on the server side" very descriptive, such detail, much debuggable.

**Comment by halt-hammerzeit** [comment]
> I fixed this with these lines in my 'start-server.babel.js':
require.extensions['.less'] = function() {};
require.extensions['.scss'] = function() {};
require.extensions['.png'] = function() {};

This clearly shows that you don't understand a thing on what's going on

**Comment by halt-hammerzeit** [comment]
> This is a problem that I have already seen in the issues without successfully correcting it.

The issue you linked was answered and was "successfully corrected"
