### ISSUE TITLE
Wait for webpack-chunks.json before starting server

### ISSUE THREAD

**Issue by inv8der** [halt-hammerzeit/universal-webpack#63]
Would it be possible to wait for the server bundle AND webpack-chunks.json to be generated before starting the server? In development, we run webpack for both client and server in parallel. The client bundle takes a while to compile, so when the server is ready to start, it continually crashes until webpack-chunks.json is available.

<img width="953" alt="screen shot 2017-02-17 at 11 12 19 am" src="https://cloud.githubusercontent.com/assets/830026/23079501/03448774-f502-11e6-84e6-890d442f8b34.png">

**Comment by halt-hammerzeit** [comment]
Is it development mode or production mode?
In production mode you should run client webpack build before the server build.
In development this error won't happen because `webpack-chunks.json` will be created the first time the command is run.

**Comment by inv8der** [comment]
This is in development. We run the following 3 processes in parallel:
```
webpack --watch --config ./webpack.config.server.dev.js
webpack-dev-server --config ./webpack.config.client.dev.js
node server.js
```
The `server.js` script is analogous to `source/start-server.js` in your example. I'm using `CleanWebpackPlugin` in both configurations, so the outputPath (including webpack-chunks.json) is deleted right before compilation starts. When the server bundle finishes, `universal-webpack` starts the server, but webpack-chunks.json has not been generated yet.

It's not really a big deal, since we use pm2 to autorestart the the `web` process. Once the client bundle is done, everything works perfectly.

**Comment by halt-hammerzeit** [comment]
> When the server bundle finishes, universal-webpack starts the server, but webpack-chunks.json has not been generated yet.

And it doesn't throw any errors in this case, does it?
It only throws when one actually calls the `chunks()` function.

Why are you using `outputPath` as part of the development process.
webpack can serve all assets to memory and from memory

**Comment by kiddo13** [comment]
I use this boilerplate as reference. Hope it useful.
https://github.com/NSLS/universal-webpack-boilerplate

**Comment by halt-hammerzeit** [comment]
The author of the boilerplate you mentioned knows me in person.
He can translate it for you.
If you're having difficulties with his particular set up then ask him.

**Comment by inv8der** [comment]
Thanks for the help! I wasn't aware the error was from calling the `chunks()` function. I took a look at the boilerplate and noticed that`npm run dev` delays starting the server for X amount of time, until the webpack-chunks.json is generated. I'll do something similar in my project.

**Comment by halt-hammerzeit** [comment]
I didn't include `wait_for_file('webpack-chunks.json')` here:
https://github.com/halt-hammerzeit/universal-webpack/blob/master/source/server.js
For `CleanWebpackPlugin` probably `wait_for_file('webpack-chunks.json')` would solve the case but I don't think using `CleanWebpackPlugin` in development mode is even needed.

**Comment by halt-hammerzeit** [comment]
I acknowledged the issue and `server()` now waits for `webpack-chunks.json` in the latest version.
