### ISSUE TITLE
Respect NODE_ENV in chunks plugin

### ISSUE THREAD

**Issue by edorivai** [halt-hammerzeit/universal-webpack#66]
I've been experiencing a little problem when running a production build, it seems that the chunks plugin *always* applies the publicPath from the devServer config:

https://github.com/halt-hammerzeit/universal-webpack/blob/master/source/chunks%20plugin.js#L56

Am I right, and if so, is this the desired behavior?

We're solving it manually like so:

webpack.config.js:

```js
{
    ...other config stuff
    devServer: process.env.NODE_ENV === 'production' ? {} : {
        ...content of devServer config
    }
}
```

**Comment by halt-hammerzeit** [comment]
How about not passing `devServer` for production at all

**Comment by halt-hammerzeit** [comment]
Theoretically I could also check the `NODE_ENV` variable but why is `devServer` even present in a production configuration

**Comment by edorivai** [comment]
Checking the NODE_ENV manually (as we do now) is absolutely something we can do, I just thought that perhaps this lib was a nice place to contain that logic. Doesn't this lib already do some checking on NODE_ENV?

I'm happy to submit a PR btw. Let me know what you think.

PS: thanks for all the work :tada:

**Comment by halt-hammerzeit** [comment]
Ok, I'll do it myself.
I was saying that maybe you should only add `devServer` option to the config only in development mode in the config generator.

**Comment by halt-hammerzeit** [comment]
Check the new version of the package

**Comment by edorivai** [comment]
Yeah okay. I kinda like that we can add `devServer` to our base config file, and as for webpack, it only gets interpreted by the `webpack-dev-server` command, right? This is what caused my initial confusion, as I was assuming that `devServer` only gets applied in a `dev` environment.
