### ISSUE TITLE
Errors during server startup don't get printed

### ISSUE THREAD

**Issue by 0xR** [halt-hammerzeit/universal-webpack#7]
My server was throwing an error at startup due to an environment variable that was missing. When I started the server using universal-webpack this error was not shown whatsoever. This results in the server stopping on start without any output in the console.

I don't have time to do a proper PR, so for now I'll submit this issue.

**Comment by halt-hammerzeit** [comment]
Well, you could have also submitted your console output and your code.
Otherwise there's no use in your issue report.

**Comment by nason** [comment]
I was running into a similar issue. I resolved it by adding some process error handlers to my `server.js` file, like so:

```javascript
/*
  Global server process error handlers
 */
process.on('uncaughtException', (err) => {
  console.log('Uncaught exception: ', err);
});

process.on('unhandledRejection', (err) => {
  console.log('Unhandled Promise Rejection for reason: ', err);
});
```

Once in place, errors preventing the server from starting were output to the console.

**Comment by halt-hammerzeit** [comment]
Fixed by @papigers in https://github.com/halt-hammerzeit/universal-webpack/pull/8
