### ISSUE TITLE
universal-webpack-prepare doesn't wait for client build

### ISSUE THREAD

**Issue by 0xR** [halt-hammerzeit/universal-webpack#72]
This might result in the server crashing because it can't find webpack-chunks.json in case the server build finishes before the client build.

**Comment by halt-hammerzeit** [comment]
`prepare` doesn't wait for client build because that's not what it's meant to do
https://github.com/halt-hammerzeit/universal-webpack/blob/master/source/prepare.js

I acknowledged the issue and `server()` now waits for `webpack-chunks.json` in the latest version.
