### ISSUE TITLE
webpack-chunks.json not found

### ISSUE THREAD

**Issue by Mordorreal** [halt-hammerzeit/universal-webpack#73]
After last update I realise that my project can't run server version because now universal-webpack will wait for webpack-chunks.json . The problem is that my webpack-chunks.json generated not in folder of server version. Universal-webpack look for webpack-chunks.json in dist/server but json created in dist . After some investigation in source code of universal-webpack I found that this function generate path to json file 
```
export function chunk_info_file_path(webpack_configuration, chunk_info_filename)
{
	return path.join(webpack_configuration.output.path, chunk_info_filename || 'webpack-chunks.json')
}
```
webpack_configuration.output.path in my webpack is 
```
path: path.join(__dirname, "..", "dist")
```
so, this is right path where webpack-chunks.json was generated. But some how this option changed on path dist/server and this is wrong because json was already generated in dist folder.

I already spend about 5 hours to this problem. Maybe you can help me to find the reason of this problem?

**Comment by halt-hammerzeit** [comment]
Well, you could add `console.log`s all over.
Say, place one here:

```js
const chunk_info_json_file_path = chunk_info_file_path(webpack_configuration, settings.chunk_info_filename)
```
And see what it outputs.

Then another one here:
```js

	// chunk filename info file path
	const output_file_path = chunk_info_file_path(webpack_configuration, options.chunk_info_filename)
```

And see if they're equal.

If not, add more `console.log`s to find out why.
5 hours is a lot.
This waiting feature was asked twice the past week.

**Comment by Mordorreal** [comment]
I found workaround:
I change my config from
```
module.exports = {
  server: {
    input: `${__dirname}/server.js`,
    output: `${__dirname}/dist/server/server.js`
  }
};
```
to
```
module.exports = {
  server: {
    input: `${__dirname}/server.js`,
    output: `${__dirname}/dist/server.js`
  }
};
```

Now server files generate not in separate folder but in one place with client bundle.
I tried to put console log and saw very strange behavior. One time it was /dist and another was /dist/server 

This is after workaround: 
```
/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist in config after server function
/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist in function
```
This is before:
```
[nodemon] restarting due to changes...
[nodemon] starting `node ./bin/start-server.js`
/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/ in config after server function
/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/ in function
("/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/server/server.js" not found)

(waiting for Webpack build to finish)
("/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/server/server.js" not found)
(waiting for Webpack build to finish)
("/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/server/server.js" not found)
(waiting for Webpack build to finish)
("/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/server/server.js" not found)
(waiting for Webpack build to finish)
("/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/server/server.js" not found)
(waiting for Webpack build to finish)
Hash: eff0886dc289c83c35c1
Version: webpack 2.3.3
Time: 39874ms
("/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/server/server.js" not found)
(waiting for Webpack build to finish)
("/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/server/server.js" not found)
(waiting for Webpack build to finish)
[nodemon] restarting due to changes...
[nodemon] starting `node ./bin/start-server.js`
/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/server/ in config after server function
/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/server/ in function
("/Users/denis_savchuk/Library/Mobile Documents/com~apple~CloudDocs/work/educa-front/dist/server/server.js" not found)
(waiting for Webpack build to finish)

```

**Comment by halt-hammerzeit** [comment]
Really, that's strange: how could the path be different during hot reload.
I guess I'll keep this issue open in case anyone else encounters it.

**Comment by indeyets** [comment]
@halt-hammerzeit we have a similar setup and see this issue too. we build server-bundle and client bundles (we have 1 server and 8+ client bundles right now) in different folders to be sure that they do not overlap. I guess `universal-webpack` needs some tests for such usecases

**Comment by halt-hammerzeit** [comment]
Well, obviously I can't debug this not having a legitimate use case.
If someone makes up a sample project with the instructions on how to reproduce the bug then I could take a look.
Or someone can debug it with `console.log`s by themselves.
