### ISSUE TITLE
Advice on best way to split app?

### ISSUE THREAD

**Issue by adailey14** [halt-hammerzeit/universal-webpack#74]
Hi halt-hammerzeit, was wondering if you could give me a little advice.

I'm in the process of updating to webpack2 and the latest version of universal-webpack and react-isomorphic-render.

My app has 2 big pieces - a client facing interface and a "business user" administration interface. In the past, I basically split these into two different copies of the webpack-react-redux-isomorphic-render-example that I glued together with koa-mount in the web service (to avoid using multiple ports). Each one has it's own webpack configuration, and I run two webpack compilations to get things compiled.

I'm trying to figure out if I should keep it that way, or treat them as two webpack entry points within a single webpack configuration. This would simplify my code a lot - but I'm not clear if two entry points would totally work within universal-webpack and react-isomorphic-render. Have you tried anything like that? Is there any reason two entry points is a bad idea?

Appreciate any advice!

**Comment by halt-hammerzeit** [comment]
Hello.
I think I would keep the two apps separate if they are truly independent, like "a website and an admin panel".
I don't have experience supporting such a setup in the long run though.

**Comment by adailey14** [comment]
Ok thanks a lot - I will stick with the two apps approach.
