### ISSUE TITLE
"chunks plugin.js" doesn't use webpack.outputFileSystem

### ISSUE THREAD

**Issue by indeyets** [halt-hammerzeit/universal-webpack#77]
Webpack has an `outputFileSystem` (see [docs](https://webpack.js.org/api/node/#compiling-to-memory)) setting which allows to override filesystem object.

If I try to use `MemoryFS` there `chunks plugin.js` of universal-webpack still uses regular `fs` (via `fs-extra`) to write the chunks info file. In my context "regular" file-system is read-only and this leads to EACCESS error

**Comment by halt-hammerzeit** [comment]
The `outputFileSystem` you linked is not a setting, it's a Node.js API.
Therefore it can't be supported.

The "read-only"ness of the "regular file-system" you mentioned doesn't prevent the server from starting.
Or do you develop your webapp on a read-only filesystem which is weird.

**Comment by indeyets** [comment]
@halt-hammerzeit why can't it be supported? `webpack.outputFileSystem` is a "pointer" to a fs-compatible object. So, plugin could just use it instead of `fs`.

Something like `const fs = compiler.ouputFileSystem;` would probably work

**Comment by halt-hammerzeit** [comment]
This implies the user starts client-side build and server-side build in the same Node.js process which isn't compatible: server-side Node.js process constantly restarts (on file changes) while client-side build only hot-reloads.
Therefore it's not compatible.

**Comment by halt-hammerzeit** [comment]
It could theoretically work like: running a production client-side build which outputs to memory and then, in the same file, running the server but one can't run a Node.js process from memory - it has to be a file.
Otherwise your case is too weird and I don't see any sanity in your feature request.

**Comment by indeyets** [comment]
It is weird indeed :)
OK. I did a local workaround and it's probably not important for most of the cases

**Comment by halt-hammerzeit** [comment]
Still you could comment on your workaround here if there happens to be another man on Earth having your use case
