### ISSUE TITLE
updated for webpack 3

### ISSUE THREAD

**Issue by AVVS** [halt-hammerzeit/universal-webpack#78]
Hey, are you still maintaining this?
There were a few updates, so was wondering if you could test it out with webpack 3 and updated peers, thanks!

**Comment by halt-hammerzeit** [comment]
What do you mean exactly.
Go test it yourself.

**Comment by AVVS** [comment]
So much anger…
Only thing I wanted to understand is whether you are willing to update peer dependencies and have time for this at all

If not - sorry to bother

**Comment by halt-hammerzeit** [comment]
> So much anger…

Same

> whether you are willing to update peer dependencies

What's wrong with them

**Comment by AVVS** [comment]
extract-text-plugin has been updated to version 3 to properly support webpack 3, therefore needs to be updated here

**Comment by halt-hammerzeit** [comment]
Talk about the plugin then.
Updated and released.

**Comment by l0c0luke** [comment]
@catamphetamine you are a horrible example of humanity...

**Comment by catamphetamine** [comment]
@l0c0luke No, you are.
Oh, and by the way, you're banned.
