### ISSUE TITLE
Why do the config files need to end with ".babel.js"?

### ISSUE THREAD

**Issue by jaraquistain** [halt-hammerzeit/universal-webpack#80]
I'm not sure if this is the appropriate place to ask so do feel free to close this, but a bit of insight or a point in the right direction would be extremely appreciated. 

I've followed the implementation instructions as suggested using `webpack.config.server.babel.js` and `webpack.config.client.babel.js` and I've managed to get everything pretty much working. My problem arose when I decided to change the names of the server/client config files and omit the `.babel` part. When I removed that and they became `webpack.config.server.js` and `webpack.config.client.js` and  calling 
```
webpack --config "./src/webpack/webpack.config.client.js"
```
would result in `SyntaxError: Unexpected token import` I.E. the file was not transpiled by babel.

I added the `.babel` back on and everything worked fine again, so my question is: what the hell is going on? I'm hoping that its just some dumb configuration I'm missing somewhere and that `universal-webpack` doesn't actually require the config files to end with `.babel.js`.

Conventions and philosophical reasons for using `[xxx].babel.js` aside I feel like the name of the config files shouldn't have anything to do with their ability to function.

**Comment by halt-hammerzeit** [comment]
This is a convention implemented in Webpack itself
