### ISSUE TITLE
Examples use es6 modules "import" in webpack config which is not supported

### ISSUE THREAD

**Issue by aight8** [halt-hammerzeit/universal-webpack#9]
When there is a simple way with babel or so to use es6 module syntax in the webpack config it would be good when the solution will be noted in the readme. Is that a not working example or which solution did you use for that?

**Comment by halt-hammerzeit** [comment]
I don't understand what you are saying

**Comment by aight8** [comment]
For the webpack configuration example you use ES6. But webpack config can't be ES6 since node 6 don't support ES6 import/export's only when its transcompiled with babel. Where this happens?

**Comment by halt-hammerzeit** [comment]
Webpack config can be ES6.
First, there's `webpack.config.babel.js`.
http://stackoverflow.com/questions/31903692/how-to-use-es6-in-webpack-config
Second, there's always `babel-register`.

**Comment by aight8** [comment]
Thank you. I use now babel-node, don't knew that. Webpack is not so good documented in some parts.

**Comment by jairusd** [comment]
well babel-node is now being deprecated i have no idea where to go from here

**Comment by KresimirCosic** [comment]
I am literally just trying to get the classic `import` and `export` rules to work with the (default named) `webpack.config.ts` (yeah, TypeScript as well), and it's inhumanely impossible to find a good documented approach. Hilarious considering how long the system has existed.

**Comment by plutotv-aaa** [comment]
@KresimirCosic , did you find a way?
